// apps/mobile/src/components/DispenserToggle.tsx
import { Pressable, Text, View } from "react-native";
import type { Dispenser } from "@rosm/core/schemas";
import { BubblerIcon, BothDispenserIcon, BottleIcon } from "./icons/DispenserIcons";

const OPTIONS: readonly {
  key: Dispenser;
  label: string;
  Icon: typeof BubblerIcon;
}[] = [
  { key: "bubbler", label: "Bubbler", Icon: BubblerIcon },
  { key: "both", label: "Both", Icon: BothDispenserIcon },
  { key: "bottle", label: "Bottle filler", Icon: BottleIcon },
];

export function DispenserToggle({
  value,
  onChange,
  label = "Dispenser",
}: {
  value: Dispenser;
  onChange: (d: Dispenser) => void;
  label?: string;
}) {
  return (
    <View className="gap-1.5">
      <Text className="text-base text-xs font-bold tracking-wider uppercase">{label}</Text>
      <View className="border-border bg-surface-deep flex-row rounded-xl border p-1">
        {OPTIONS.map(({ key, label: optLabel, Icon }) => {
          const selected = value === key;
          const color = selected ? "#ffffff" : "#0c0d0a";
          return (
            <Pressable
              key={key}
              onPress={() => onChange(key)}
              accessibilityRole="button"
              accessibilityState={{ selected }}
              className={`flex-1 flex-row items-center justify-center gap-1.5 rounded-lg py-2.5 ${
                selected ? "bg-base shadow-sm" : ""
              }`}
            >
              <Icon size={16} color={color} />
              <Text className={`text-xs font-bold ${selected ? "text-surface" : "text-base"}`}>
                {optLabel}
              </Text>
            </Pressable>
          );
        })}
      </View>
    </View>
  );
}

// apps/site/src/components/DispenserToggle.svelte
<script lang="ts">
  import type { Dispenser } from "@rosm/core/schemas";
  import BubblerIcon from "@/components/icons/BubblerIcon.svelte";
  import BothDispenserIcon from "@/components/icons/BothDispenserIcon.svelte";
  import BottleIcon from "@/components/icons/BottleIcon.svelte";

  const OPTIONS = [
    { key: "bubbler", label: "Bubbler", Icon: BubblerIcon },
    { key: "both", label: "Both", Icon: BothDispenserIcon },
    { key: "bottle", label: "Bottle filler", Icon: BottleIcon },
  ] as const;

  let {
    value,
    onChange,
    label = "Dispenser",
  }: { value: Dispenser; onChange: (d: Dispenser) => void; label?: string } = $props();
</script>

<div class="flex flex-col gap-1">
  <span class="text-xs font-medium tracking-wide text-neutral-500 uppercase">{label}</span>
  <div class="flex gap-1 rounded-md bg-neutral-100 p-0.5">
    {#each OPTIONS as { key, label: optLabel, Icon } (key)}
      <button
        type="button"
        onclick={() => onChange(key)}
        class="flex flex-1 items-center justify-center gap-1 rounded py-1 text-xs font-medium transition {value ===
        key
          ? 'bg-white text-neutral-900 shadow-sm'
          : 'text-neutral-500 hover:text-neutral-800'}"
      >
        <Icon size={14} />
        <span>{optLabel}</span>
      </button>
    {/each}
  </div>
</div>
