// apps/site/src/components/FountainLeaderboard.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { apiFetch } from "@/lib/api";
  import type { LeaderboardEntry } from "@/lib/leaderboard";

  // Ranked list of the OSM contributors who've updated the most distinct points
  // through the app. Splits into two compact tables side-by-side on desktop
  // (ranks 1–5 left, 6–10 right), each with its own header; on mobile they stack
  // into a single column. While loading, shows headers with pulsing skeleton rows.
  let { class: className = "" }: { class?: string } = $props();

  let leaders = $state<LeaderboardEntry[]>([]);
  let loading = $state(true);

  onMount(() => {
    let alive = true;
    apiFetch("/api/leaderboard")
      .then((r) => (r.ok ? r.json() : null))
      .then((j: { leaders: LeaderboardEntry[] } | null) => {
        if (alive && j) leaders = j.leaders;
      })
      .catch(() => {})
      .finally(() => {
        if (alive) loading = false;
      });
    return () => {
      alive = false;
    };
  });

  const columns = $derived(
    [leaders.slice(0, 5), leaders.slice(5, 10)].filter((c) => c.length > 0),
  );
</script>

{#snippet headerRow(extraClass: string)}
  <div
    class="text-ink-dim border-ink/15 grid grid-cols-[1.5rem_1fr_auto] items-baseline gap-3 border-b pb-2 font-mono text-[0.65rem] font-medium tracking-[0.14em] uppercase {extraClass}"
  >
    <span>#</span>
    <span>Contributor</span>
    <span class="text-right">Points</span>
  </div>
{/snippet}

{#snippet skeletonRow()}
  <div
    class="border-paper-line grid grid-cols-[1.5rem_1fr_auto] items-center gap-3 border-b py-2.5"
  >
    <span class="bg-ink/10 h-3 w-3 animate-pulse rounded"></span>
    <span class="bg-ink/10 h-3 w-28 animate-pulse rounded"></span>
    <span class="bg-ink/10 h-3 w-6 animate-pulse justify-self-end rounded"></span>
  </div>
{/snippet}

{#if loading}
  <div class="flex flex-col gap-x-16 sm:flex-row {className}">
    {#each [0, 1] as ci (ci)}
      <div
        class="w-full sm:max-w-xs {ci === 1
          ? '[&>*:last-child]:border-b-0'
          : 'sm:[&>*:last-child]:border-b-0'}"
      >
        {@render headerRow(ci > 0 ? "hidden sm:grid" : "")}
        {#each Array(5) as _, i (i)}
          {@render skeletonRow()}
        {/each}
      </div>
    {/each}
  </div>
{:else if leaders.length === 0}
  <p class="text-ink-dim text-sm {className}">
    No contributors yet — be the first to update a fountain.
  </p>
{:else}
  <div class="flex flex-col gap-x-16 sm:flex-row {className}">
    {#each columns as col, ci (ci)}
      <div
        class="w-full sm:max-w-xs {ci === columns.length - 1
          ? '[&>*:last-child]:border-b-0'
          : 'sm:[&>*:last-child]:border-b-0'}"
      >
        {@render headerRow(ci > 0 ? "hidden sm:grid" : "")}
        {#each col as l, i (l.username)}
          <div
            class="border-paper-line grid grid-cols-[1.5rem_1fr_auto] items-baseline gap-3 border-b py-2.5"
          >
            <span class="text-ink-dim font-mono text-sm tabular-nums">{ci * 5 + i + 1}</span>
            <span class="min-w-0 font-medium">
              <a
                href={`https://www.openstreetmap.org/user/${encodeURIComponent(l.username)}`}
                target="_blank"
                rel="noopener noreferrer"
                class="decoration-ink/20 hover:decoration-ink block truncate underline-offset-4 hover:underline"
              >
                {l.username}
              </a>
            </span>
            <span class="text-ink-dim text-right text-sm tabular-nums">{l.points}</span>
          </div>
        {/each}
      </div>
    {/each}
  </div>
{/if}

// components/FountainLeaderboard.tsx
"use client";

import { useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import type { LeaderboardEntry } from "@/app/api/leaderboard/route";

// Ranked list of the OSM contributors who've updated the most distinct points
// through the app. Splits into two compact tables side-by-side on desktop
// (ranks 1–5 left, 6–10 right), each with its own header; on mobile they stack
// into a single column, so only the first column's header shows. Renders nothing until
// there's data — an empty leaderboard reads as broken, not "no contributors yet".
export default function FountainLeaderboard({ className = "" }: { className?: string }) {
  const [leaders, setLeaders] = useState<LeaderboardEntry[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let alive = true;
    apiFetch("/api/leaderboard")
      .then((r) => (r.ok ? r.json() : null))
      .then((j: { leaders: LeaderboardEntry[] } | null) => {
        if (alive && j) setLeaders(j.leaders);
      })
      .catch(() => {})
      .finally(() => {
        if (alive) setLoading(false);
      });
    return () => {
      alive = false;
    };
  }, []);

  // While the fetch is in flight, show the headers with pulsing skeleton rows so
  // the section doesn't pop in.
  if (loading) {
    return (
      <div className={`flex flex-col gap-x-16 sm:flex-row ${className}`}>
        {[0, 1].map((ci) => (
          <div
            key={ci}
            className={`w-full sm:max-w-xs ${
              ci === 1 ? "[&>*:last-child]:border-b-0" : "sm:[&>*:last-child]:border-b-0"
            }`}
          >
            <Row
              header
              rank="#"
              name="Contributor"
              points="Points"
              className={ci > 0 ? "hidden sm:grid" : ""}
            />
            {Array.from({ length: 5 }).map((_, i) => (
              <SkeletonRow key={i} />
            ))}
          </div>
        ))}
      </div>
    );
  }

  // Loaded, but nobody's edits have been attributed yet. Say so explicitly
  // instead of hiding the section — a blank gap reads as a bug.
  if (leaders.length === 0) {
    return (
      <p className={`text-ink-dim text-sm ${className}`}>
        No contributors yet — be the first to update a fountain.
      </p>
    );
  }

  const columns = [leaders.slice(0, 5), leaders.slice(5, 10)].filter((c) => c.length > 0);

  return (
    <div className={`flex flex-col gap-x-16 sm:flex-row ${className}`}>
      {columns.map((col, ci) => (
        <div
          key={ci}
          className={`w-full sm:max-w-xs ${
            ci === columns.length - 1
              ? "[&>*:last-child]:border-b-0"
              : "sm:[&>*:last-child]:border-b-0"
          }`}
        >
          <Row
            header
            rank="#"
            name="Contributor"
            points="Points"
            className={ci > 0 ? "hidden sm:grid" : ""}
          />
          {col.map((l, i) => (
            <Row
              key={l.username}
              rank={String(ci * 5 + i + 1)}
              name={
                <a
                  href={`https://www.openstreetmap.org/user/${encodeURIComponent(l.username)}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="decoration-ink/20 hover:decoration-ink block truncate underline-offset-4 hover:underline"
                >
                  {l.username}
                </a>
              }
              points={l.points}
            />
          ))}
        </div>
      ))}
    </div>
  );
}

// Placeholder body row while the leaderboard loads. Same grid as Row so widths
// match; the bars pulse to signal loading rather than a real (empty) value.
function SkeletonRow() {
  return (
    <div className="border-paper-line grid grid-cols-[1.5rem_1fr_auto] items-center gap-3 border-b py-2.5">
      <span className="bg-ink/10 h-3 w-3 animate-pulse rounded" />
      <span className="bg-ink/10 h-3 w-28 animate-pulse rounded" />
      <span className="bg-ink/10 h-3 w-6 animate-pulse justify-self-end rounded" />
    </div>
  );
}

// One grid row shared by the header and body so the three columns line up.
function Row({
  rank,
  name,
  points,
  header = false,
  className = "",
}: {
  rank: string;
  name: React.ReactNode;
  points: React.ReactNode;
  header?: boolean;
  className?: string;
}) {
  const base = "grid grid-cols-[1.5rem_1fr_auto] items-baseline gap-3";
  if (header) {
    return (
      <div
        className={`${base} text-ink-dim border-ink/15 border-b pb-2 font-mono text-[0.65rem] font-medium tracking-[0.14em] uppercase ${className}`}
      >
        <span>{rank}</span>
        <span>{name}</span>
        <span className="text-right">{points}</span>
      </div>
    );
  }
  return (
    <div className={`${base} border-paper-line border-b py-2.5`}>
      <span className="text-ink-dim font-mono text-sm tabular-nums">{rank}</span>
      <span className="min-w-0 font-medium">{name}</span>
      <span className="text-ink-dim text-right text-sm tabular-nums">{points}</span>
    </div>
  );
}
