// apps/site/src/components/AudienceToggle.svelte
<script lang="ts">
  import { User } from "phosphor-svelte";
  import type { Audience } from "@rosm/core/schemas";
  import DogIcon from "@/components/icons/DogIcon.svelte";
  import BothAudienceIcon from "@/components/icons/BothAudienceIcon.svelte";

  const OPTIONS = [
    { key: "humans", label: "Humans", Icon: User },
    { key: "both", label: "Both", Icon: BothAudienceIcon },
    { key: "dogs", label: "Dogs", Icon: DogIcon },
  ] as const;

  let {
    value,
    onChange,
    label = "Intended for",
  }: { value: Audience; onChange: (a: Audience) => void; label?: string } = $props();
</script>

<div class="flex flex-col gap-1">
  <span class="text-xs font-medium tracking-wide text-neutral-500 uppercase">{label}</span>
  <div class="flex gap-1 rounded-md bg-neutral-100 p-0.5">
    {#each OPTIONS as { key, label: optLabel, Icon } (key)}
      <button
        type="button"
        onclick={() => onChange(key)}
        class="flex flex-1 items-center justify-center gap-1 rounded py-1 text-xs font-medium capitalize transition {value ===
        key
          ? 'bg-white text-neutral-900 shadow-sm'
          : 'text-neutral-500 hover:text-neutral-800'}"
      >
        <Icon size={14} />
        <span>{optLabel}</span>
      </button>
    {/each}
  </div>
</div>

// apps/mobile/src/components/AudienceToggle.tsx
import type { ComponentType } from "react";
import { Pressable, Text, View } from "react-native";
import { User } from "phosphor-react-native";
import type { Audience } from "@rosm/core/schemas";
import { DogIcon } from "./icons/DogIcon";
import { BothAudienceIcon } from "./icons/BothAudienceIcon";

const OPTIONS: readonly {
  key: Audience;
  label: string;
  Icon: ComponentType<{ size?: number; color?: string }>;
}[] = [
  { key: "humans", label: "Humans", Icon: User },
  { key: "both", label: "Both", Icon: BothAudienceIcon },
  { key: "dogs", label: "Dogs", Icon: DogIcon },
];

export function AudienceToggle({
  value,
  onChange,
  label = "Intended for",
}: {
  value: Audience;
  onChange: (a: Audience) => void;
  label?: string;
}) {
  return (
    <View className="gap-1.5">
      <Text className="text-base text-xs font-bold tracking-wider uppercase">{label}</Text>
      <View className="border-border bg-surface-deep flex-row rounded-xl border p-1">
        {OPTIONS.map(({ key, label: optLabel, Icon }) => {
          const selected = value === key;
          const color = selected ? "#ffffff" : "#0c0d0a";
          return (
            <Pressable
              key={key}
              onPress={() => onChange(key)}
              accessibilityRole="button"
              accessibilityState={{ selected }}
              className={`flex-1 flex-row items-center justify-center gap-1.5 rounded-lg py-2.5 ${
                selected ? "bg-base shadow-sm" : ""
              }`}
            >
              <Icon size={16} color={color} />
              <Text className={`text-xs font-bold ${selected ? "text-surface" : "text-base"}`}>
                {optLabel}
              </Text>
            </Pressable>
          );
        })}
      </View>
    </View>
  );
}
