// apps/site/src/components/PointDetailsForm.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { Snowflake } from "phosphor-svelte";
  import type { Audience, Dispenser, EditExtras } from "@rosm/core/schemas";
  import { audienceFromTags } from "@/lib/audience";
  import { dispenserFromTags } from "@/lib/dispenser";
  import AudienceToggle from "@/components/AudienceToggle.svelte";
  import DispenserToggle from "@/components/DispenserToggle.svelte";

  const QUICK_TAGS = [
    "Not draining",
    "Low water pressure",
    "One fountain not running",
    "Bottle filler not running",
  ];

  let {
    tags,
    busy,
    submitLabel,
    submitIcon,
    submitClassName = "bg-green-600 hover:bg-green-700",
    onSubmit,
    isRemoved = false,
    isOutOfOrder = false,
    isBroken = false,
  }: {
    tags: Record<string, string>;
    busy: boolean;
    submitLabel: string;
    submitIcon?: Snippet;
    submitClassName?: string;
    onSubmit: (extras?: EditExtras) => void;
    isRemoved?: boolean;
    isOutOfOrder?: boolean;
    isBroken?: boolean;
  } = $props();

  // Derive initial values from tags (tags identity is stable per popup).
  let seasonal = $state(tags.seasonal === "yes");
  let audience = $state<Audience>(audienceFromTags(tags));
  let dispenser = $state<Dispenser>(dispenserFromTags(tags));
  let note = $state(tags.note ?? tags.description ?? "");

  function toggleQuickTag(tagText: string) {
    if (note.includes(tagText)) {
      note = note
        .split(";")
        .map((s) => s.trim())
        .filter((s) => s !== tagText)
        .join("; ");
    } else {
      note = note ? `${note}; ${tagText}` : tagText;
    }
  }

  function buildExtras(): EditExtras | undefined {
    const trimmed = note.trim();
    if (isRemoved) {
      return trimmed ? { note: trimmed } : undefined;
    }
    const extras: EditExtras = { audience, dispenser };
    if (seasonal && !isOutOfOrder) extras.seasonal = true;
    if (trimmed) extras.note = trimmed;
    return Object.keys(extras).length ? extras : undefined;
  }
</script>

<div class="flex flex-col gap-2.5">
  {#if isRemoved}
    <div class="rounded border border-red-200 bg-red-50 p-2 text-xs font-medium text-red-700">
      Confirm marking this fountain as removed.
    </div>
  {:else}
    <AudienceToggle value={audience} onChange={(a) => (audience = a)} />
    <DispenserToggle value={dispenser} onChange={(d) => (dispenser = d)} />
    {#if !isOutOfOrder}
      <label
        class="flex cursor-pointer items-center justify-between rounded-lg border p-2.5 transition {seasonal
          ? 'border-sky-500 bg-sky-50/70'
          : 'border-neutral-200 bg-neutral-50 hover:bg-neutral-100'}"
      >
        <div class="flex items-center gap-2.5">
          <input
            type="checkbox"
            bind:checked={seasonal}
            class="size-4 cursor-pointer rounded border-neutral-300 accent-sky-600"
          />
          <div class="flex flex-col">
            <span class="text-xs font-bold text-neutral-900">Seasonal fountain</span>
            <span class="text-[11px] font-medium text-neutral-500">Runs only part of the year</span>
          </div>
        </div>
        <Snowflake
          size={18}
          class={seasonal ? "text-sky-600" : "text-neutral-400"}
          weight={seasonal ? "fill" : "regular"}
        />
      </label>
    {/if}
  {/if}

  {#if isBroken}
    <div class="flex flex-col gap-1.5 pt-1">
      <span class="text-[11px] font-bold tracking-wider text-neutral-600 uppercase">
        What's wrong with the fountain?
      </span>
      <div class="flex flex-wrap gap-1">
        {#each QUICK_TAGS as tag (tag)}
          <button
            type="button"
            onclick={() => toggleQuickTag(tag)}
            class="rounded border px-2 py-1 text-[11px] font-medium transition {note.includes(tag)
              ? 'border-amber-600 bg-amber-500 text-white'
              : 'border-neutral-200 bg-neutral-50 text-neutral-700 hover:bg-neutral-100'}"
          >
            {tag}
          </button>
        {/each}
      </div>
    </div>
  {/if}

  <textarea
    bind:value={note}
    placeholder={isBroken ? "Describe what's wrong…" : "Add a public note…"}
    rows={2}
    maxlength={255}
    class="resize-none rounded-md border border-neutral-300 px-2 py-1.5 text-xs text-neutral-800 placeholder:text-neutral-400 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none"
  ></textarea>
  <button
    disabled={busy}
    onclick={() => onSubmit(buildExtras())}
    class="flex items-center justify-center gap-1.5 rounded-md py-2 text-xs font-semibold text-white shadow-sm transition disabled:opacity-50 {submitClassName}"
  >
    {@render submitIcon?.()}
    {submitLabel}
  </button>
</div>

// apps/mobile/src/components/PointDetailsForm.tsx
import { useMemo, useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { CheckCircleIcon, SnowflakeIcon } from "phosphor-react-native";
import type { Audience, Dispenser, EditExtras } from "@rosm/core/schemas";
import { audienceFromTags } from "@rosm/core/audience";
import { dispenserFromTags } from "@rosm/core/dispenser";
import { AudienceToggle } from "./AudienceToggle";
import { DispenserToggle } from "./DispenserToggle";

const QUICK_TAGS = [
  "Not draining",
  "Low water pressure",
  "One fountain not running",
  "Bottle filler not running",
];

type Props = {
  tags: Record<string, string>;
  submitLabel: string;
  SubmitIcon?: typeof CheckCircleIcon;
  submitBox?: string;
  onSubmit: (extras?: EditExtras) => void;
  onCancel?: () => void;
  isRemoved?: boolean;
  isOutOfOrder?: boolean;
  isBroken?: boolean;
};

export function PointDetailsForm({
  tags,
  submitLabel,
  SubmitIcon = CheckCircleIcon,
  submitBox = "bg-green-600",
  onSubmit,
  onCancel,
  isRemoved = false,
  isOutOfOrder = false,
  isBroken = false,
}: Props) {
  // Derive initial values from tags — recalculated when `tags` identity changes.
  const defaults = useMemo(
    () => ({
      audience: audienceFromTags(tags),
      dispenser: dispenserFromTags(tags),
      seasonal: tags.seasonal === "yes",
      note: tags.note ?? tags.description ?? "",
    }),
    [tags],
  );

  const [audience, setAudience] = useState<Audience>(defaults.audience);
  const [dispenser, setDispenser] = useState<Dispenser>(defaults.dispenser);
  const [seasonal, setSeasonal] = useState(defaults.seasonal);
  const [note, setNote] = useState(defaults.note);

  function toggleQuickTag(tagText: string) {
    if (note.includes(tagText)) {
      const updated = note
        .split(";")
        .map((s) => s.trim())
        .filter((s) => s !== tagText)
        .join("; ");
      setNote(updated);
    } else {
      setNote(note ? `${note}; ${tagText}` : tagText);
    }
  }

  function handleSubmit() {
    const trimmed = note.trim();
    if (isRemoved) {
      onSubmit(trimmed ? { note: trimmed } : undefined);
      return;
    }
    const extras: EditExtras = { audience, dispenser };
    if (seasonal && !isOutOfOrder) extras.seasonal = true;
    if (trimmed) extras.note = trimmed;
    onSubmit(extras);
  }

  return (
    <View className="gap-3.5">
      {isRemoved ? (
        <View className="rounded-xl border border-red-300 bg-red-100 p-4">
          <Text className="text-sm font-bold text-red-950">
            Confirm marking this fountain as removed.
          </Text>
        </View>
      ) : (
        <>
          <AudienceToggle value={audience} onChange={setAudience} />
          <DispenserToggle value={dispenser} onChange={setDispenser} />

          {/* Seasonal checkbox hidden on out of order page */}
          {!isOutOfOrder ? (
            <Pressable
              onPress={() => setSeasonal((s) => !s)}
              accessibilityRole="checkbox"
              accessibilityState={{ checked: seasonal }}
              accessibilityLabel="Seasonal fountain"
              className={`flex-row items-center justify-between rounded-xl border p-4 ${
                seasonal ? "border-sky-500 bg-sky-50" : "border-paper-line bg-paper-deep"
              }`}
            >
              <View className="flex-row items-center gap-3">
                <View
                  className={`h-6 w-6 items-center justify-center rounded-lg border ${
                    seasonal ? "border-sky-600 bg-sky-600" : "border-paper-line bg-white"
                  }`}
                >
                  {seasonal ? <Text className="text-xs font-black text-white">✓</Text> : null}
                </View>
                <View className="gap-0.5">
                  <Text className="text-ink text-sm font-bold">Seasonal fountain</Text>
                  <Text className="text-ink-dim text-xs font-semibold">
                    Runs only part of the year
                  </Text>
                </View>
              </View>
              <SnowflakeIcon
                size={20}
                color={seasonal ? "#0284c7" : "#57544a"}
                weight={seasonal ? "fill" : "regular"}
              />
            </Pressable>
          ) : null}
        </>
      )}

      {/* 4th Category "Working but broken" issue details + quick tag pills */}
      {isBroken ? (
        <View className="gap-2 pt-1">
          <Text className="text-ink text-xs font-bold tracking-wider uppercase">
            What&apos;s wrong with the fountain?
          </Text>
          <View className="flex-row flex-wrap gap-1.5 pb-1">
            {QUICK_TAGS.map((tag) => {
              const active = note.includes(tag);
              return (
                <Pressable
                  key={tag}
                  onPress={() => toggleQuickTag(tag)}
                  className={`rounded-lg border px-2.5 py-1.5 ${
                    active ? "border-amber-600 bg-amber-500" : "border-paper-line bg-paper-deep"
                  }`}
                >
                  <Text className={`text-xs font-bold ${active ? "text-white" : "text-ink"}`}>
                    {tag}
                  </Text>
                </Pressable>
              );
            })}
          </View>
        </View>
      ) : null}

      <View className="gap-1.5">
        <Text className="text-ink text-xs font-bold tracking-wider uppercase">
          {isBroken ? "Details / Note" : "Public Note"}
        </Text>
        <TextInput
          value={note}
          onChangeText={setNote}
          placeholder={isBroken ? "Describe what's wrong…" : "Add a public note (optional)"}
          placeholderTextColor="#57544a"
          multiline
          maxLength={255}
          className="border-paper-line text-ink min-h-20 rounded-xl border bg-white p-3.5 text-sm font-medium"
        />
      </View>

      <View className="flex-row gap-3 pt-2">
        {onCancel ? (
          <Pressable
            onPress={onCancel}
            accessibilityRole="button"
            className="border-paper-line bg-paper-deep flex-1 items-center justify-center rounded-xl border px-4 py-3"
          >
            <Text className="text-ink text-base font-bold">Back</Text>
          </Pressable>
        ) : null}
        <Pressable
          onPress={handleSubmit}
          accessibilityRole="button"
          className={`flex-1 flex-row items-center justify-center gap-2 rounded-xl px-4 py-3 ${submitBox}`}
        >
          <SubmitIcon size={18} color="#ffffff" weight="bold" />
          <Text className="text-base font-bold text-white">{submitLabel}</Text>
        </Pressable>
      </View>
    </View>
  );
}
